### ISSUE TITLE
ImportError: No module named picasa

### ISSUE THREAD

**Issue by lahdekorpi** [legoktm/picasa#1]
Installation fails with pip and from sources pulled from GitHub:

```
Traceback (most recent call last):
  File "/usr/local/bin/picasa", line 9, in <module>
    load_entry_point('picasa-downloader==0.1.1', 'console_scripts', 'picasa')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named picasa
```

Using Debian Wheezy

**Comment by Cantello** [comment]
Same here, installed via pip on Debian Squeeze. Fails with the above error message, except for a newer version number (1.0) and different line numbers.

**Comment by gnbl** [comment]
That's because picasa.py does not get installed for some reason, while picasa.exe is generated.
For use with Python 3: `C:\Python34\Scripts>python ..\Tools\Scripts\2to3.py -w picasa.py`.

But that does not help either, unmaintained `gdata` (see https://github.com/legoktm/picasa/issues/2) does not play nice with `atom`:

```
Traceback (most recent call last):
  File "I:\Python34\Scripts\picasa-script.py", line 9, in <module>
    load_entry_point('picasa-downloader==0.1.1', 'console_scripts', 'picasa')()
  File "I:\Python34\Scripts\picasa.py", line 38, in main
    albums = pws.GetUserFeed(user=username).entry
  File "I:\Python34\lib\site-packages\gdata\photos\service.py", line 239, in GetUserFeed
    return self.GetFeed(uri, limit=limit)
  File "I:\Python34\lib\site-packages\gdata\photos\service.py", line 182, in GetFeed
    return self.Get(uri, converter=gdata.photos.AnyFeedFromString)
  File "I:\Python34\lib\site-packages\gdata\service.py", line 1072, in Get
    headers=extra_headers)
  File "I:\Python34\lib\site-packages\atom\__init__.py", line 94, in optional_warn_function
    return f(*args, **kwargs)
  File "I:\Python34\lib\site-packages\atom\service.py", line 186, in request
    auth_token = self.token_store.find_token(url)
  File "I:\Python34\lib\site-packages\atom\token_store.py", line 85, in find_token
    if url in self._tokens:
TypeError: unhashable type: 'Url'
```

@legoktm Please update the landing sites (pypi, readme) with a warning about these issues.

**Comment by lahdekorpi** [comment]
Wait, there's a Windows version?

**Comment by wzieba** [comment]
still doesn't resolve the problem, I've got the same TypeError
